version: '3'

services:
  db:
    image: mysql
    env_file:
      - ./src/.env
    environment:
      - MYSQL_ROOT_PASSWORD="123456789"

  web:
    build: .
    volumes:
      - ./usr/src/app:/usr/src/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
